### ISSUE TITLE
Uniform buffer's field value is chaotic in compute shader

### ISSUE THREAD

**Issue by grenlight** [gfx-rs/wgpu-rs#36] opened 2019-07-11 12:54 UTC
I have defined a ```uniform``` struct named ```FluidUniform```, in the compute shader, , use ```buffer``` to record the uniform value in order, then, use  ```copy_buffer_to_buffer``` copy buffer's value to ```staging_buffer``` and print it, the value of the FluidUniform's ```e``` field is chaotic, and some values are for other fields (such as ```lattice_num```).

```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FluidUniform {
    // e: [[f32; 2]; 9],
    e: [f32; 18],
    lattice_size: [f32; 2],
    lattice_num: [f32; 2],
    weight: [f32; 9],
    swap: i32,
}

// compute shader
layout(set = 0, binding = 0) uniform FluidUniform {
    // vec2 e[9];
    float e[18];
    vec2 lattice_size;
    vec2 lattice_num;
    float weight[9];
    int swap;
};
...
layout (set = 0, binding = 3) buffer FluidBuffer { 
    FluidCell fluidCells[];    
};

// write e's value to buffer
for (int j = 0; j < 6; j ++) {
    fluidCells[j].color[0] = e[j * 3];
    fluidCells[j].color[1] = e[j * 3 + 1];
    fluidCells[j].color[2] = e[j * 3 + 2];
}
```
Print ```staging_buffer```'s value

```rust
encoder.copy_buffer_to_buffer(&self.fluid_buffer, 0, &self.staging_buffer, 0, fluid_buf_range);
self.app_view.device.get_queue().submit(&[encoder.finish()]);
self.staging_buffer.map_read_async(0, fluid_buf_range, |result: wgpu::BufferMapAsyncResult<&[FluidCell]>| {
    println!("{:?}", result.unwrap().data);
});
```

**Comment by grenlight** [comment] 2019-07-12 06:36
I uploaded an example, only tested on macOS: [https://github.com/grenlight/idroid_demo](https://github.com/grenlight/idroid_demo)
related rust file: [src/fluid/lbm_flow.rs](https://github.com/grenlight/idroid_demo/blob/master/src/fluid/lbm_flow.rs)
compute shader file: [shader/fluid/collide.comp](https://github.com/grenlight/idroid_demo/blob/master/shader/fluid/collide.comp)

**Comment by kvark** [comment] 2019-07-12 13:58
> validateComputeFunctionArguments:771: failed assertion `Compute Function(main0): argument _34[0] from buffer(0) with offset(0) and length(128) has space for 128 bytes, but argument has a length(464).'

**Comment by kvark** [comment] 2019-07-12 14:04
The problem is caused by the fact SPIRV-Cross generates the shader with `vec4` everywhere instead of single floats:
```
struct FluidUniform
{
    float4 e[18];
    float2 lattice_size;
    float2 lattice_num;
    float4 weight[9];
    int swap;
};
```
Definition on the app side:
```
layout(set = 0, binding = 0) uniform FluidUniform {
    // 表示D2Q9离散速度模型速度空间的速度配置
    // vec2 e[9];
    float e[18];
    // lattice 在正规化坐标空间的大小
    vec2 lattice_size;
    vec2 lattice_num;
    float weight[9];
    // 0： f_tex10， 1: f_tex11
    int swap;
};
```

**Comment by grenlight** [comment] 2019-07-18 07:16
Since I think SPIRV-Cross is unlikely to have such a low-level error, I went to see the issues related to the SPIRV-Cross and glslang projects. As mentioned in [glslang/issues/1475](https://github.com/KhronosGroup/glslang/issues/1475), in in[ OpenGL Spec](https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf), the alignment rules for uniform members are as follows:
> 1. If the member is a scalar consuming N basic machine units, the base alignment is N.
> 2. If the member is a two- or four-component vector with components consuming N basic machine units, the base alignment is 2N or 4N, respectively.
> 3. If the member is a three-component vector with components consuming N basic machine units, the base alignment is 4N.
> 4. If the member is an array of scalars or vectors, the base alignment and array stride are set to match the base alignment of a single array element, according to rules (1), (2), and (3), and rounded up to the base alignment of a vec4. The array may have padding at the end; the base offset of the member following the array is rounded up to the next multiple of the base alignment.

The result of this spec is: ```[f32, x],[[f32; 2], x], [[f32; 3], x]```'s  array stride all equal to 16 bytes. 

So, does wgpu need a mechanism to match the alignment in glslang? Or is this entirely part of what the user should handle?

**Comment by grenlight** [comment] 2019-07-18 07:56
I defined a test ```Uniform Buffer``` struct and print out the spirv txt use shaderc:
```
// uniform structure in shader
layout(set = 0, std140) uniform FluidUniform {
    vec2 e[9];
    vec3 e0[9];
    float e1[18];
    ivec3 e2[9];
    int e3[18];
};

// spirv text
"               OpName %FluidUniform \"FluidUniform\""
"               OpMemberName %FluidUniform 0 \"e\""
"               OpMemberName %FluidUniform 1 \"e0\""
"               OpMemberName %FluidUniform 2 \"e1\""
"               OpMemberName %FluidUniform 3 \"e2\""
"               OpMemberName %FluidUniform 4 \"e3\""
"               OpName %__0 \"\""
"               OpDecorate %gl_GlobalInvocationID BuiltIn GlobalInvocationId"
"               OpDecorate %_arr_float_uint_3 ArrayStride 4"
"               OpMemberDecorate %FluidCell 0 Offset 0"
"               OpDecorate %_runtimearr_FluidCell ArrayStride 12"
"               OpMemberDecorate %FluidBuffer 0 Offset 0"
"               OpDecorate %FluidBuffer BufferBlock"
"               OpDecorate %_ DescriptorSet 0"
"               OpDecorate %_ Binding 1"
"               OpDecorate %_arr_v2float_uint_9 ArrayStride 16"
"               OpDecorate %_arr_v3float_uint_9 ArrayStride 16"
"               OpDecorate %_arr_float_uint_18 ArrayStride 16"
"               OpDecorate %_arr_v3int_uint_9 ArrayStride 16"
"               OpDecorate %_arr_int_uint_18 ArrayStride 16"
"               OpMemberDecorate %FluidUniform 0 Offset 0"
"               OpMemberDecorate %FluidUniform 1 Offset 144"
"               OpMemberDecorate %FluidUniform 2 Offset 288"
"               OpMemberDecorate %FluidUniform 3 Offset 576"
"               OpMemberDecorate %FluidUniform 4 Offset 720"
"               OpDecorate %FluidUniform Block"
```

**Comment by grenlight** [comment] 2019-07-18 11:47
Since glsl is unrelated to WebGPU API, closed it.

**Comment by kvark** [comment] 2019-07-18 13:28
Let's keep it open since it will likely affect more people and is relevant to our examples.

**Comment by cwfitzgerald** [comment] 2020-12-01 07:38
Since std140 is a well-known enemy at this point and the age and unfindability of this issue, I'm going to close it. I do still think we should have an std140 overview somewhere or at least some links to the nice crates that deal with it for you.

**Closed by cwfitzgerald** 2020-12-01 07:38 UTC
Labels: bug
