### ISSUE TITLE
shadow example fails with some error related to resizing the window

### ISSUE THREAD

**Issue by yutannihilation** [gfx-rs/wgpu-rs#403] opened 2020-06-21 05:13 UTC
I see this failure when I tried to run shadow example on the current master. But, if I use the `v0.5` tag, it runs without errors. It seems this fails after 28c826182f9336050a4ed9fa0f30a0dc6451f1c3.

The primary cause of this error is the weird behavior of my window manager (I use GNOME3 + wayland on Manjaro Linux); it resizes the window size soon after the window created (c.f. https://github.com/nannou-org/nannou/issues/575#issuecomment-620311038). But, even if my GNOME3 behaves strangely, I think the framework should handle the resize properly (and probably it does before 28c826182f9336050a4ed9fa0f30a0dc6451f1c3). Were there any change on wgpu that the `Extent` might be used concurrently?

https://github.com/gfx-rs/wgpu-rs/blob/64648522265e69ebc3a0b507e89315b8025baf9d/examples/framework.rs#L150-L152

```
$ cargo run --example shadow
    Updating crates.io index
    Updating git repository `https://github.com/gfx-rs/wgpu`
    Updating git repository `https://github.com/gfx-rs/gfx-extras`
    Updating git repository `https://github.com/gfx-rs/naga`
   Compiling wgpu v0.5.0 (/home/yutani/repo/wgpu-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 15.05s
     Running `target/debug/examples/shadow`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Extent { width: 800, height: 570, depth: 1 }`,
 right: `Extent { width: 800, height: 600, depth: 1 }`: Extent state must match extent from view', <::std::macros::panic macros>:5:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2020-06-21T04:39:20Z ERROR gfx_memory::heaps] Heaps still have 1 types live on drop
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(256) is still used
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(2048) is still used
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(16384) is still used
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(131072) is still used
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(10485760) is still used
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(1024) is still used
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(2232320) is still used
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(2101248) is still used
[2020-06-21T04:39:20Z ERROR gfx_memory::allocator::linear] Not all allocation from LinearAllocator was freed
[2020-06-21T04:39:20Z ERROR gfx_descriptor::allocator] DescriptorAllocator is dropped
[2020-06-21T04:39:20Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-vkDestroyDevice-device-00378 (1901072314)] : Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x5587877824d0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x5587877af700, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x5587877824d0[], VkCommandBuffer 0x5587877af700[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
    object info: (type: DEVICE, hndl: 94040581743824), (type: COMMAND_BUFFER, hndl: 94040581928704)

[2020-06-21T04:39:20Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-vkDestroyDevice-device-00378 (1901072314)] : Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x5587877824d0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x55878779c440, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x5587877824d0[], VkCommandBuffer 0x55878779c440[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
    object info: (type: DEVICE, hndl: 94040581743824), (type: COMMAND_BUFFER, hndl: 94040581850176)

...snip...

[2020-06-21T04:39:20Z ERROR gfx_backend_vulkan]
    VALIDATION [VUID-vkDestroyDevice-device-00378 (1901072314)] : Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x5587877824d0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x30000000003, type = VK_OBJECT_TYPE_COMMAND_POOL; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x5587877824d0[], VkCommandPool 0x30000000003[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
    object info: (type: DEVICE, hndl: 94040581743824), (type: COMMAND_POOL, hndl: 3298534883331)

VUID-vkDestroyInstance-instance-00629(ERROR / SPEC): msgNum: -1958900200 - Validation Error: [ VUID-vkDestroyInstance-instance-00629 ] Object 0: handle = 0x5587872727a0, type = VK_OBJECT_TYPE_INSTANCE; Object 1: handle = 0x20000000002, type = VK_OBJECT_TYPE_SURFACE_KHR; | MessageID = 0x8b3d8e18 | OBJ ERROR : For VkInstance 0x5587872727a0[], VkSurfaceKHR 0x20000000002[] has not been destroyed. The Vulkan spec states: All child objects created using instance must have been destroyed prior to destroying instance (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyInstance-instance-00629)
    Objects: 2
        [0] 0x5587872727a0, type: 1, name: NULL
        [1] 0x20000000002, type: 1000000000, name: NULL

```

### Backtrace

<details>

```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  13: wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass_impl
             at ./<::std::macros::panic macros>:5
  14: wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass
             at /home/yutani/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c7be940/wgpu-core/src/command/render.rs:328
  15: wgpu::backend::direct::<impl wgpu::Context for wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>::command_encoder_end_render_pass
             at src/backend/direct.rs:946
  16: <wgpu::RenderPass as core::ops::drop::Drop>::drop
             at src/lib.rs:1838
  17: core::ptr::drop_in_place
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/ptr/mod.rs:177
  18: <shadow::Example as shadow::framework::Example>::render
             at examples/shadow/main.rs:811
  19: shadow::framework::run_async::{{closure}}::{{closure}}
             at examples/shadow/../framework.rs:182
  20: winit::platform_impl::platform::sticky_exit_callback
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
  21: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::{{closure}}
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/event_loop.rs:524
  22: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::redraw_triggers::{{closure}}
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/event_loop.rs:678
  23: winit::platform_impl::platform::wayland::window::WindowStore::for_each_redraw_trigger
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/window.rs:552
  24: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::redraw_triggers
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/event_loop.rs:667
  25: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/event_loop.rs:523
  26: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/event_loop.rs:455
  27: winit::platform_impl::platform::EventLoop<T>::run
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:644
  28: winit::event_loop::EventLoop<T>::run
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  29: shadow::framework::run_async::{{closure}}
             at examples/shadow/../framework.rs:118
  30: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/future.rs:44
  31: futures_executor::local_pool::block_on::{{closure}}
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  32: futures_executor::local_pool::run_executor::{{closure}}
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/local.rs:262
  34: std::thread::local::LocalKey<T>::with
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/local.rs:239
  35: futures_executor::local_pool::run_executor
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  36: futures_executor::local_pool::block_on
             at /home/yutani/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  37: shadow::framework::run
             at examples/shadow/../framework.rs:204
  38: shadow::main
             at examples/shadow/main.rs:818
  39: std::rt::lang_start::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  40: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  41: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  42: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  43: std::panicking::try
             at src/libstd/panicking.rs:281
  44: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  45: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  46: std::rt::lang_start
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  47: main
  48: __libc_start_main
  49: _start
```

</details>

**Comment by kvark** [comment] 2020-06-22 16:01
Thank you for filing!
Looks like a dupe of #352

**Closed by kvark** 2020-06-22 16:01 UTC

**Comment by yutannihilation** [comment] 2020-06-22 23:30
Aw, sorry I didn't notice the issue ... I'll keep my eye on it. Thanks!
