### ISSUE TITLE
UBO array's will be misaligned if their size isn't a power of 2

### ISSUE THREAD

**Issue by ocboogie** [gfx-rs/wgpu-rs#53] opened 2019-08-03 01:46 UTC
I was using the example from lyon, [here](https://github.com/nical/lyon/tree/master/examples/wgpu_advanced), and I came across are weird issue. If the `Primitive` type's size wasn't a power of 2 (e.g. 16, 32, 64), excluding 4 or 8, the array would be misaligned in the shader, making the first primitive render fine, but subsequent primitives wouldn't.
I created a repo, [here](https://github.com/ocboogie/wgpu-issue), to isolate the problem, with two branches, one showing the problem with the size of 8 bytes, and one working with the size of 32 bytes. There's a comment, [here](https://github.com/ocboogie/wgpu-issue/blob/master/src/main.rs#L11), explaining how to make the 8 byte version work. Similarly, there's a comment, [here](https://github.com/ocboogie/wgpu-issue/blob/working-with-32-bytes/src/main.rs#L16) explaining how to make the 32 byte version stop working.
I've tried Vulkan and DirectX 12, both seeming to be having this issue.
I'm not sure if this is a problem directly with wgpu-rs, or if it's a problem with wgpu, rendy, or gfx-hal, but I'll just post it here, because that's what I'm directly working with.

**Comment by kvark** [comment] 2019-08-03 02:30
Thank you for filing the issue!
Looks like a duplicate of #36

**Comment by ocboogie** [comment] 2019-08-03 03:32
Ah, I'm sorry. I even saw that, didn't think it was related. My mistake.
Although I am using `shaderc-rs` not using `glsl-to-spirv`, nor is any of my dependencies. My understanding is that `glsl-to-spirv` was the problem.

**Comment by ocboogie** [comment] 2019-08-03 03:36
Oh wait. I might understand now. From what I've gathered from #44, `glsl-to-spirv` is deprecated, and therefore won't fix this issue. Whereas, `shaderc-rs` is still being updated so it should release a fix for this soon.
Is my understanding correct?

**Comment by kvark** [comment] 2019-08-03 04:10
Well, I still need to look deeper into the issue. It consists of two parts:
  1. making sure that GLSL -> SPIRV has consistent and predictable alignment of fields. This is not (yet?) a concern for upstream WebGPU, since it only cares about SPIR-V (and WHLSL atm), but it is a concern for many users who would want to use GLSL for either wgpu-rs or gfx-rs
  2. validating the shader in wgpu-native and/or adding artificial padding at the shader translation stage, so that the user-provided UBOs match

**Comment by kvark** [comment] 2021-06-03 05:22
This is an old issue that is likely fixed. We are moving to `wgpu` now, so please re-open there if still a bug!

**Closed by kvark** 2021-06-03 05:22 UTC
