### ISSUE TITLE
How would I pass a specialization constant?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [gfx-rs/wgpu-rs#521] opened 2020-08-20 21:20 UTC
Just browsing the examples and playing around I can't see where I would pass a specilization constant, thus I'm asking this question.

**Comment by cwfitzgerald** [comment] 2020-08-20 21:23
wgpu doesn't currently support specialization constants, though limited support is planned in wgsl: https://github.com/gpuweb/gpuweb/pull/886

**Comment by kvark** [comment] 2020-08-21 00:01
I'd love me some specialization constants too! Note however that the working group just recently agreed to introduce them, and in a very limited capacity. For example, you can't have them to affect the workgroup size, binding index, or any array size.

**Comment by JonathanWoollett-Light** [comment] 2020-08-21 01:05
@kvark Gotta say not being able to use them for array size really puts a downer on them, in summing a vector if you can't use them to specify the number of outputs you need (1 for each workgroup) then you simply end up duplicating the whole buffer. Turns what could be 1gb+1mb into 2gb.

**Comment by grovesNL** [comment] 2020-08-21 01:29
Even without specialization constants, it shouldn't be necessary to duplicate buffers. Do you have an example of what you're trying to do? Maybe there is another approach that could avoid the use of specialization constants.

With a bit more work it's also possible to manually patch the shader (GLSL or SPIR-V) to set a constant value (e.g. recreating the shader module). This wouldn't be a great workaround, but could still work ok if it's really necessary somewhere.

**Comment by kvark** [comment] 2020-08-24 04:31
@JonathanWoollett-Light I'm not sure what the question is, tbh. What is the problem you are seeing in `sasum` case that you are trying to solve?

> it requires the output buffer be the size of input buffer 

Neither input or output buffers are sized from the shader point of view, so this is not something that needs a specialization constant.

**Comment by JonathanWoollett-Light** [comment] 2020-08-24 07:02
I didn't know the shaders saw them as unsized, I was thinking if the shader sees 2 buffers as simply:

```
layout(binding = 0) buffer Buffer1 {
    float a[];
};
layout(binding = 1) buffer Buffer2 {
    float b[];
};
```

Then when defining the size of these buffers in Rust they would both need to be the same size.

Guessing I was wrong here? If so, that's good, my problem is not actually a problem then.

**Comment by kvark** [comment] 2020-08-24 15:08
Please just try to explain what the problem is, as clearly as possible. Where and why do you require the specialization constants?

**Comment by JonathanWoollett-Light** [comment] 2020-09-09 03:36
@kvark I have been reminded of this. Apologies for not answering before, I got distracted.

Here's my attempt at a clearer explanation:

When carrying out any scan/reduce operation (e.g. summing all values), it is practically impossible (from my understanding) to communicate and synchronize between work groups efficiently. For example when carrying out a sum operation, each workgroup sums its segment of the data and then writes this sum to a buffer.

This buffer need only be of size `(n / w).ceil()` where `n` is the length of the data and `w` is the workgroup size.
But without being able to specify the size the array in glsl using a specialization constant it is of size `n`.

For example when summing 1 billion f32s (4gb) with a workgroup size of 1024 it would use a buffer of 4gb when it only needs a buffer of 4mb, this is a very apparant difference.

As always I am very cautious to assert things, so if I am wrong here I apologise and please enlighten me.

**Comment by kvark** [comment] 2020-09-09 04:50
Ok, so I don't see why you'd need a specialization constant for the size of the array. Just use an unsized array:
```
layout(binding = 0) buffer Buffer {
    float a[];
};
```

**Comment by JonathanWoollett-Light** [comment] 2020-09-09 05:05
It was my understanding that when defining an array of undefined size it simply had as many elements as invocations. I think that is/was my key misunderstanding here if I'm understanding now.

**Comment by kvark** [comment] 2020-09-09 05:07
Ah I see. Ok, to clarify, that array will have as many elements as fits in the binding size of the array (unrelated to the invocation count). I guess on that note we can close the issue? Please feel free to re-open!

**Closed by kvark** 2020-09-09 05:07 UTC
Labels: enhancement, question

**Comment by ajtribick** [comment] 2020-09-27 14:44
I ran into this while looking at whether it would be possible to adapt [VkFFT](https://github.com/DTolm/VkFFT) to wgpu-rs. The compute shaders there use a bunch of specialization constants, unfortunately it looks like they are used to set workgroup sizes and the size of shared arrays so I guess that's a no-go.

**Comment by kvark** [comment] 2020-09-28 03:12
After we implement specialization constants in wgpu, we could technically make a native-only extension that allows to use them for defining work group sizes and dynamic arrays. This is going to be some work though, and the end result will not be running on the Web.

**Comment by cwfitzgerald** [comment] 2020-09-28 06:05
If you are looking to specialize things today and are targeting native, you can use the spirv_cross crate to specialize the constants directly in the spirv. It isn't quite as useful as you can't do it on native, but it works today.
