### ISSUE TITLE
Examples fails on Mac OS mid 2014

### ISSUE THREAD

**Issue by edap** [gfx-rs/wgpu-rs#138] opened 2019-12-13 08:49 UTC
I have just pulled master and run `cargo update`. The example with the triangle worked. The cube map one still fails:

```
cargo run --example cube RUST_BACKTRACE=1
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/examples/cube RUST_BACKTRACE=1`
2019-12-13 09:46:57.163 cube[5832:37615] -[MTLIGAccelBuffer addDebugMarker:range:]: unrecognized selector sent to instance 0x7fcf42d3ebd0
[2019-12-13T08:46:57Z ERROR relevant] Values of this type can't be dropped!
[1]    5832 segmentation fault  cargo run --example cube RUST_BACKTRACE=1
```

I have the same error (`[MTLIGAccelBuffer addDebugMarker:range:]: unrecognized selector sent to instance`) for the examples `mipmap`, `capture`, `shadow`, `msaa-line`, `skybox`, `hello-compute`.
`hello-triangle` and `describe` are working.
The examples: `describe` and `hello-triangle`

I am on Mac OS "El Capitan", MacBook Pro (Retina, 13-inch, Mid 2014).
GPU Intel Iris 1536 MB.

**Comment by kvark** [comment] 2019-12-14 02:51
Dupe of https://github.com/gfx-rs/gfx/issues/3098

**Closed** 2020-03-04 20:42 UTC
Labels: bug
