### ISSUE TITLE
Is it possible to remove the need for cargo features?

### ISSUE THREAD

**Issue by Lokathor** [gfx-rs/wgpu-rs#63] opened 2019-08-15 19:17 UTC
I talked about this a bit with @grovesNL on Discord, but basically:

Can the crate be more automatic about backend selection? So that by default the user doesn't have to select any cargo features to just "make it work however".

This could even be a feature that's just the default feature where you get a correct backend picked for you, or you can turn off default features and then turn on just the one backend you want.

I know cargo isn't the best and it's very hard to make it play nice with platform specific stuff like this, but this is an important ergonomics goal.

**Comment by kvark** [comment] 2019-08-15 19:29
Theoretically possible, practically still a challenge to implement.
Closing as a duplicate of https://github.com/gfx-rs/wgpu/issues/252

**Closed by kvark** 2019-08-15 19:29 UTC
