### ISSUE TITLE
vulkan: vkCreateSwapChainKHR called with invalid imageExtent on resize

### ISSUE THREAD

**Issue by lcnr** [gfx-rs/wgpu-rs#24] opened 2019-06-16 20:36 UTC
wgpu version: 2.3
gpu:             
> description: VGA compatible controller
     product: HD Graphics 620
     vendor: Intel Corporation
     physical id: 2
     bus info: pci@0000:00:02.0
     version: 02
     width: 64 bits
     clock: 33MHz
     capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
     configuration: driver=i915 latency=0
     resources: irq:132 memory:b0000000-b0ffffff memory:a0000000-afffffff ioport:4000(size=64) memory:c0000-dffff

os: 
>NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

----

When running a modified version of the triangle example with `cargo run --features wgpu/vulkan`, I get the following errors when trying to resize the window:

> [2019-06-16T20:28:11Z ERROR gfx_backend_vulkan] [DS] Object: 0x55ecdc79b140 | vkCreateSwapChainKHR() called with imageExtent = (1024,768), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1853,1025), minImageExtent = (1853,1025), maxImageExtent = (1853,1025). The spec valid usage text states 'imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)

Sometimes this causes the program to exit when trying to go to full screen. The actual problem can be found here: https://github.com/lcnr/wgpu_err

**Comment by kvark** [comment] 2019-06-17 01:55
Thank you! Looks like we (here or `winit`) aren't taking hidpi properly.

**Comment by adudney** [comment] 2019-12-05 03:48
X11, Fedora 30
AdapterInfo { name: "Intel(R) HD Graphics 620 (Kaby Lake GT2)", vendor: 32902, device: 22806, device_type: IntegratedGpu }
wgpu-rs 44fa1bc2fa208fa92f80944253e0da56cb7ac1fe
winit 0.20.0-alpha4

I've got a similar reproduction case with all wgpu calls being done on a background thread with the foreground thread running winit and passing events to the background thread. The background thread only handles resize events once per frame, before calling "swap_chain.get_next_texture()" (the swap chain has vsync enabled)

In this config, the log output differs based on when the main thread receives a resize event from winit.

If a resize event occurs after the swap chain has given a texture, it only logs a warning:
```
2019-12-04 20:32:21,514 INFO  [test::render] Before `frame = swap_chain.get_next_texture()`
2019-12-04 20:32:21,525 INFO  [test::render] After `frame = swap_chain.get_next_texture()`
2019-12-04 20:32:21,526 INFO  [test] Resize event received: 1912 499
2019-12-04 20:32:21,530 INFO  [test::render] Before `drop(frame)`
2019-12-04 20:32:21,530 WARN  [wgpu_core::swap_chain] present failed: OutOfDate
2019-12-04 20:32:21,530 INFO  [test::render] After `drop(frame)`
2019-12-04 20:32:21,531 INFO  [test::render] Resize handled by renderer
```

However, if the resize occurs while the swap chain is waiting on a texture, it logs an error:
```
2019-12-04 20:32:21,962 INFO  [test::render] Before `frame = swap_chain.get_next_texture()`
2019-12-04 20:32:21,963 WARN  [wgpu_core::swap_chain] acquire_image() failed (OutOfDate), reconfiguring swapchain
2019-12-04 20:32:21,965 INFO  [test] Resize event received: 956 1027
2019-12-04 20:32:21,965 ERROR [gfx_backend_vulkan] 
VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0)] : vkCreateSwapchainKHR() called with imageExtent = (1912,495), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (956,1027), minImageExtent = (956,1027), maxImageExtent = (956,1027). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
object info: (type: DEVICE, hndl: 94677958135872)

2019-12-04 20:32:21,976 INFO  [test::render] After `frame = swap_chain.get_next_texture()`
2019-12-04 20:32:21,989 INFO  [test::render] Before `drop(frame)`
2019-12-04 20:32:21,990 INFO  [test::render] After `drop(frame)`
2019-12-04 20:32:21,990 INFO  [test::render] Resize handled by renderer
```

Additionally, sometimes the frame before a resize will print a warning about failing to present:
```
2019-12-04 20:32:20,814 INFO  [test::render] Before `frame = swap_chain.get_next_texture()`
2019-12-04 20:32:20,827 INFO  [test::render] After `frame = swap_chain.get_next_texture()`
2019-12-04 20:32:20,831 INFO  [test::render] Before `drop(frame)`
2019-12-04 20:32:20,831 WARN  [wgpu_core::swap_chain] present failed: OutOfDate
2019-12-04 20:32:20,832 INFO  [test::render] After `drop(frame)`
2019-12-04 20:32:20,832 INFO  [test::render] Before `frame = swap_chain.get_next_texture()`
2019-12-04 20:32:20,832 WARN  [wgpu_core::swap_chain] acquire_image() failed (OutOfDate), reconfiguring swapchain
2019-12-04 20:32:20,835 INFO  [test] Resize event received: 956 1027
2019-12-04 20:32:20,836 ERROR [gfx_backend_vulkan] 
VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0)] : vkCreateSwapchainKHR() called with imageExtent = (1467,1027), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (956,1027), minImageExtent = (956,1027), maxImageExtent = (956,1027). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
object info: (type: DEVICE, hndl: 94677958135872)

2019-12-04 20:32:20,849 INFO  [test::render] After `frame = swap_chain.get_next_texture()`
2019-12-04 20:32:20,865 INFO  [test::render] Before `drop(frame)`
2019-12-04 20:32:20,867 INFO  [test::render] After `drop(frame)`
2019-12-04 20:32:20,867 INFO  [test::render] Resize handled by renderer
```

**Comment by cwfitzgerald** [comment] 2020-12-01 07:31
Harmony reports this as fixed in a newer version of wgpu, so I'm going to close this. If it's still an issue on the latest master, feel free to re-open with new info.

**Closed by cwfitzgerald** 2020-12-01 07:31 UTC
Labels: bug, help wanted
