### ISSUE TITLE
Example generate white window

### ISSUE THREAD

**Issue by edap** [gfx-rs/wgpu-rs#97] opened 2019-10-15 21:09 UTC
Running `cargo run --example hello-triangle` does not produce any error but the window is white.

**Comment by rukai** [comment] 2019-10-15 21:30
OS, GPU, git/crates.io?

**Comment by edap** [comment] 2019-10-16 07:06
I am pulling from master.

I am on Mac OS "El Capitan", MacBook Pro (Retina, 13-inch, Mid 2014).
GPU Intel Iris 1536 MB.

**Comment by kvark** [comment] 2019-10-16 13:06
@edap what about other examples?

**Comment by kvark** [comment] 2019-10-16 15:40
I can't repro on another Intel GPU laptop (on macos 10.15). Looks like a swapchain/layers/presentation problem.

**Comment by mlindner** [comment] 2019-10-17 00:37
@edap Try running with  RUST_BACKTRACE=1 and provide that output. That might help people.

**Comment by kvark** [comment] 2019-10-17 00:56
I wonder if it's related to how winit creates a layer.

**Comment by edap** [comment] 2019-10-17 06:24
I have tried `export RUST_BACKTRACE=1 ` before launching the cargo command and ` RUST_BACKTRACE=1  cargo run --example hello-triangle` but it has no effect on the output.

**Comment by rukai** [comment] 2019-10-17 07:03
It wouldn't, RUST_BACKTRACE only affects panic messages.

**Comment by kvark** [comment] 2019-10-17 14:38
Would be good to have a simple Metal-rs example that creates a window and renders to it, to rule out if it's a problem with gfx-rs, wgpu-rs, or winit.

**Comment by kvark** [comment] 2019-10-17 19:54
I found a platform to reproduce on. I confirm that everything is rendered correctly but the layer contents are not visible. It's either a problem with layer properties we set by gfx-backend-metal, or with the way `winit` creates the layer/NSView.

**Comment by kvark** [comment] 2019-10-26 02:33
This will be fixed once we move to gfx-0.4

**Comment by kvark** [comment] 2019-10-31 15:54
Should be resolved by #3049

**Closed by kvark** 2019-10-31 15:54 UTC
Labels: bug
