### ISSUE TITLE
Docs.rs failed to build WGPU 0.5

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu-rs#244] opened 2020-04-07 00:53 UTC

**Comment by grovesNL** [comment] 2020-04-07 03:24
Opened https://github.com/rust-lang/rust/issues/70874

**Comment by iulianR** [comment] 2020-04-21 19:32
Related issue seems to be fixed. Any update?

**Comment by kvark** [comment] 2020-04-21 20:14
I suppose we need to try releasing a patch version.

**Comment by grovesNL** [comment] 2020-04-21 20:19
I think we can request the docs be rebuilt manually

**Comment by grovesNL** [comment] 2020-04-22 00:09
Created https://github.com/rust-lang/docs.rs/issues/726

**Comment by grovesNL** [comment] 2020-04-22 02:08
Fixed by rust-lang/docs.rs#726

https://docs.rs/wgpu/0.5.0/wgpu/

**Closed by grovesNL** 2020-04-22 02:08 UTC
Labels: bug

**Comment by iulianR** [comment] 2020-04-22 07:30
Thanks for the quick response and fix. Glad I checked to see issue status as I've been waiting for a while and I thought the issue is more complex than that :)
